# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Neolude-Pool
  vmImage: windows-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: Resource Group
    azureResourceManagerConnection: 'azure-devops-service-connection'
    subscriptionId: 'c84ab836-320a-4451-8302-864ca7447aab'
    location: 'Brazil South'
    templateLocation: 'Linked artifact'
    csmFile: '.\bicep\azureDataFactory.bicep'
    deploymentMode: 'Complete'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-devops-service-connection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az datafactory trigger delete --factory-name "datafactoryb2v42c6lrdhxs" --resource-group "Lab-Neolude-BI" --name "adf-pipeline-trigger"'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-devops-service-connection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az datafactory trigger create --factory-name "datafactoryb2v42c6lrdhxs" --resource-group "Lab-Neolude-BI" --properties $(System.DefaultWorkingDirectory)\bicep\scheduleTrigger.json  --name "adf-pipeline-trigger"'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-devops-service-connection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az datafactory trigger start --factory-name "datafactoryb2v42c6lrdhxs" --resource-group "Lab-Neolude-BI" --name "adf-pipeline-trigger"'
