trigger: none
parameters:
  - name: 'customerName'
    displayName: 'Nome do cliente para o qual serão criados os recursos'
    type: string

variables:
  environment: 'dev'
  department: 'bi'
  location: 'brazilsouth'
  resourceGroupName: '${{ parameters.customerName }}-$(department)-$(environment)-$(location)'
  subscriptionId: 'c56f173d-86ef-45e2-9a11-d3d887738b21'
  servicePrincipalConnection: 'AzureDevOpsPipelines'
  agentPool: 'Azure Pipelines'

stages:
  - stage: 'CreateResources'
    displayName: 'Create Azure Data Factory Resources'
    pool: 
      name: $(agentPool)
      vmImage: windows-latest
    jobs:
      - job: 'CreateResourceGroup'
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Subscription'
              azureResourceManagerConnection: $(servicePrincipalConnection)
              subscriptionId: $(subscriptionId)
              location: $(location)
              templateLocation: 'Linked artifact'
              csmFile: '.\bicep\resourceGroup.bicep'
              overrideParameters: '-resourceGroupName $(resourceGroupName) -resourceGroupLocation $(location)'
              deploymentMode: 'Incremental'

      - job: 'CreateAzureDataFactory'
        dependsOn: 'CreateResourceGroup'
        condition: succeeded()
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: $(servicePrincipalConnection)
              subscriptionId: $(subscriptionId)
              resourceGroupName: $(resourceGroupName)
              location: $(location)
              action: 'Create Or Update Resource Group'
              templateLocation: 'Linked artifact'
              csmFile: '.\bicep\azureDataFactory.bicep'
              deploymentMode: 'Incremental'
              
      - job: 'CreateSQLDatabase'
        dependsOn: 'CreateResourceGroup'
        condition: succeeded()
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: $(servicePrincipalConnection)
              subscriptionId: $(subscriptionId)
              resourceGroupName: $(resourceGroupName)
              location: $(location)
              action: 'Create Or Update Resource Group'
              templateLocation: 'Linked artifact'
              csmFile: '.\bicep\sqlServer.bicep'
              overrideParameters: '-sqlServerAdminLogin ${{ parameters.sqlServerAdminLogin }} -sqlServerAdminPassword ${{ parameters.sqlServerAdminPassword }}'
              deploymentMode: 'Incremental'
                
