trigger: none
parameters:
  - name: 'customerName'
    displayName: 'Nome do cliente para o qual serão criados os recursos'
    type: string
  - name: 'sqlServerAdminLogin'
    displayName: 'SQL server admin user name'
    type: string
  - name: 'sqlServerAdminPassword'
    displayName: 'SQL server admin password'
    type: string
  - name: 'baseURL'
    displayName: 'API URL'
    default: 'https://data-api.neolude.com.br/'
    type: string    
  - name: 'apiSecureString'
    displayName: 'API token'
  - name: 'relativeURL'
    displayName: 'API relativeURL eg: path https://<baseURL>/relativeURL'
    type: string
    default: '/'    

variables:
  environment: 'dev'
  department: 'bi'
  location: 'brazilsouth'
  resourceGroupName: '${{ parameters.customerName }}-$(department)-$(environment)-$(location)'
  subscriptionId: 'c56f173d-86ef-45e2-9a11-d3d887738b21'
  servicePrincipalConnection: 'AzureDevOpsPipelines'
  agentPool: 'Azure Pipelines'

stages:
  - stage: 'CreateResources'
    displayName: 'Create Azure Data Factory Resources'
    pool: 
      name: $(agentPool)
      vmImage: windows-latest
    jobs:
      - job: 'CreateResourceGroup'
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Subscription'
              azureResourceManagerConnection: $(servicePrincipalConnection)
              subscriptionId: $(subscriptionId)
              location: $(location)
              templateLocation: 'Linked artifact'
              csmFile: '.\bicep\resourceGroup.bicep'
              overrideParameters: '-resourceGroupName $(resourceGroupName) -resourceGroupLocation $(location)'
              deploymentMode: 'Incremental'

      - job: 'CreateAzureDataFactory'
        dependsOn: 'CreateResourceGroup'
        condition: succeeded()
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: $(servicePrincipalConnection)
              subscriptionId: $(subscriptionId)
              resourceGroupName: $(resourceGroupName)
              location: $(location)
              action: 'Create Or Update Resource Group'
              templateLocation: 'Linked artifact'
              csmFile: '.\bicep\azureDataFactory.bicep'
              deploymentMode: 'Incremental'
              
      - job: 'CreateSQLDatabase'
        dependsOn: 'CreateResourceGroup'
        condition: succeeded()
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: $(servicePrincipalConnection)
              subscriptionId: $(subscriptionId)
              resourceGroupName: $(resourceGroupName)
              location: $(location)
              action: 'Create Or Update Resource Group'
              templateLocation: 'Linked artifact'
              csmFile: '.\bicep\sqlServer.bicep'
              overrideParameters: '-sqlServerAdminLogin ${{ parameters.sqlServerAdminLogin }} -sqlServerAdminPassword ${{ parameters.sqlServerAdminPassword }}'
              deploymentMode: 'Incremental'
                
      - job: 'CreateAzureDataFactoryLinkedServices'
        dependsOn: ['CreateSQLDatabase', 'CreateAzureDataFactory']
        condition: succeeded()
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: $(servicePrincipalConnection)
              subscriptionId: $(subscriptionId)
              resourceGroupName: $(resourceGroupName)
              location: $(location)
              action: 'Create Or Update Resource Group'
              templateLocation: 'Linked artifact'
              csmFile: '.\bicep\azureDataFactoryLinkedServices.bicep'
              overrideParameters: '-sqlServerAdminLogin ${{ parameters.sqlServerAdminLogin }} -sqlServerAdminPassword ${{ parameters.sqlServerAdminPassword }} -baseURL ${{ parameters.baseURL }} -apiSecureString ${{ parameters.apiSecureString }}'
              deploymentMode: 'Incremental'

      - job: 'CreateAzureDataFactoryDataSets'
        dependsOn: 'CreateAzureDataFactoryLinkedServices'
        condition: succeeded()
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(servicePrincipalConnection)'
              subscriptionId: '$(subscriptionId)'
              resourceGroupName: '$(resourceGroupName)'
              location: '$(location)'
              action: 'Create Or Update Resource Group'
              templateLocation: 'Linked artifact'
              csmFile: '.\bicep\azureDataFactoryDataSets.bicep'
              overrideParameters: '-relativeURL ${{ parameters.relativeURL}} -schemaName neolude -tableName videos'
              deploymentMode: 'Incremental'              

  - stage: 'CreateTablesOnDatabase'
    displayName: 'Create schemas and tables on sql database'
    # dependsOn: 'CreateResources'
    # condition: succeeded()
    pool:
      name: $(agentPool)
      vmImage: windows-latest
    jobs:
      - job: 'CreateSchemasAndTablesOnDatabase'
        steps:
          - task: UseDotNet@2
            inputs:
              version: '8.x'
              performMultiLevelLookup: true
          - task: DotNetCoreCLI@2
            inputs:
              command: 'run'
              projects: '.\dotnet-scripts\dotnet-scripts.csproj'
              arguments: '$(resourceGroupName)-sql-server $(resourceGroupName)-sql-database ${{ parameters.sqlServerAdminLogin }} ${{ parameters.sqlServerAdminPassword }}' 
              workingDirectory: '.\dotnet-scripts'