# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Neolude-Pool
  vmImage: windows-latest

variables:
  SUBSCRIPTION_ID: 'c84ab836-320a-4451-8302-864ca7447aab'
  LOCATION: 'Brazil South'
  TEMPLATE_PATH: '.\bicep\resourceGroup.bicep'
  TEMPLATE_PARAM_PATH: '.\bicep\resourceGroupParam.bicepparam'
  SERVICE_PRINCIPAL_CONNECTION: 'azure-devops-service-connection'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: $(SERVICE_PRINCIPAL_CONNECTION)
    subscriptionId: $(SUBSCRIPTION_ID)
    location: $(LOCATION)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)\$(TEMPLATE_PATH)'
    overrideParameters: 'resourceGroupName=Neolude-Pipeline resourceGroupLocation-brazilsouth'
    deploymentMode: 'Incremental'

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'azure-devops-service-connection'
#     scriptType: 'ps'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az datafactory trigger delete --factory-name "datafactoryb2v42c6lrdhxs" --resource-group "Lab-Neolude-BI" --name "adf-pipeline-trigger" --yes'
# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'azure-devops-service-connection'
#     scriptType: 'ps'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az datafactory trigger create --factory-name "datafactoryb2v42c6lrdhxs" --resource-group "Lab-Neolude-BI" --properties $(System.DefaultWorkingDirectory)\bicep\scheduleTrigger.json  --name "adf-pipeline-trigger"'
# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'azure-devops-service-connection'
#     scriptType: 'ps'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az datafactory trigger start --factory-name "datafactoryb2v42c6lrdhxs" --resource-group "Lab-Neolude-BI" --name "adf-pipeline-trigger"'
